### ISSUE TITLE
[Feature Request] Translate links

### ISSUE THREAD

**Issue by omperus** [avm99963/translateselectedtext#17]
Hey, love your extension and the privacy features, I would really like a feature to right click a link and have a button to automatically open the translated webpage from the link on a new tab to a pre-set language.
Thanks for your work.

**Comment by avm99963** [comment]
Thank you so much for your kind words, I really appreciate it :))

That'd be awesome! I've created a new issue in the new issue tracker so I don't forget to add this feature, it shouldn't be very hard to do it:

- https://bugs.avm99963.com/p/translateselectedtext/issues/detail?id=7 (you can star the issue if you want to receive email notifications)

However, I don't have much free time now, so I can't promise I'll do this soon :/
