### ISSUE TITLE
Cannot drag and drop languages in optionsV2 page

### ISSUE THREAD

**Issue by GoogleCodeExporter** [avm99963/translateselectedtext#5]
```
What steps will reproduce the problem?
1. Open Chrome 40+
2. Show options page in chrome://extensions.
3. Try to reorder elements in the languages panel.

What is the expected output? What do you see instead?
It should drag and drop languages in the panel, but instead it doesn't do 
anything.

Please use labels and text to provide additional information.
It seems like it might be a sortable incompatibility with the new options page 
behaviour.
```

Original issue reported on code.google.com by `jocdelad...@gmail.com` on 1 Jan 2015 at 7:12

Attachments:
- [Screenshot 2015-01-01 20.10.26.png](https://storage.googleapis.com/google-code-attachments/translateselectedtext/issue-5/comment-0/Screenshot 2015-01-01 20.10.26.png)

**Comment by avm99963** [comment]
Actually this was fixed Apr 7, 2015.

See https://code.google.com/p/chromium/issues/detail?id=445817#c16
